kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: banana-dev-api-claim
  namespace: banana
  labels:
    app: banana-dev-api

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2.8Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: banana-dev-api-volume
  namespace: banana
  labels:
    type: local
    app: banana-dev-api

spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/banana-dev-api/
